# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/br',
                'doc_host': 'https://callmephilip.github.io',
                'git_url': 'https://github.com/callmephilip/br',
                'lib_path': 'br'},
  'syms': {'br.core': {'br.core.foo': ('core.html#foo', 'br/core.py')}}}
