# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/br/',
                'doc_host': 'https://callmephilip.github.io',
                'git_url': 'https://github.com/callmephilip/br/',
                'lib_path': 'br'},
  'syms': {'br.core': {'br.core.generate_image': ('core.html#generate_image', 'br/core.py')}}}
