"""various API adapters for the core breakfast roll service"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_adapters.ipynb.

# %% auto 0
__all__ = ['br_starlette', 'index']

# %% ../01_adapters.ipynb 2
from starlette.applications import Starlette
from starlette.responses import JSONResponse
from starlette.routing import Route
from starlette.responses import HTMLResponse
from starlette.testclient import TestClient
from .core import generate_image

# %% ../01_adapters.ipynb 3
async def index(request): return JSONResponse({'url': generate_image()})

br_starlette = Starlette(debug=True, routes=[Route('/', index)])
