name: Deploy to GitHub Pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps: [uses: fastai/workflows/quarto-ghp@master]
  build_server:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        run: docker build -t br -f Dockerfile .
      - name: Run image
        run: docker run -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -p 5001:5001 br
